KTraining/Models/TopicViewModel.cs
using KTraining.Resources.ViewModels;
using KTreining.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTraining.Models
{
    public class TopicViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class AddTopicViewModel
    {
        [Required(
            ErrorMessageResourceName="FieldNameRequired",
            ErrorMessageResourceType=typeof(Common)
            )]
        [Display(
            Name="Name",
            ResourceType=typeof(Common)
            )]
        public string Name { get; set; }
    }

    public class TypeQuestionsViewModel
    {
        public int TopicId { get; set; }

        public string TopicName { get; set; }
    }

    public class SelectTopicAutomaticRandViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool Selected { get; set; }

        public int QuestionCount { get; set; }
    }

    public class SelectTopicManualRandViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool SelectedCloseQ { get; set; }

        public bool SelectedOpenQ { get; set; }

        public int OpenQCount { get; set; }

        public int CloseQCount { get; set; }
    }

    public class TopicQuestionsManualViewModel
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public List<SelectCloseQuestionViewModel> CloseQuestions { get; set; }

        public List<SelectOpenQuestionViewModel> OpenQuestions { get; set; }
    }

    public class TopicQuestionsAutomaticViewModel
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public List<SelectCloseQuestionViewModel> CloseQuestions { get; set; }
    }
}

KTraining/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Models;
using KTreining.Model;
using KTraining.Resources.Controllers;

namespace KTraining.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TopicController : BaseController
    {
        // GET: Topics
        [HttpGet]
        public ActionResult Topics()
        {
            var teacher = this.userService.GetTeacherByAppUserId(this.User.Identity.GetUserId());
            var topics = this.topicService.GetForTeacher(teacher.Id);
            var viewModel = topics.ToList().ConvertAll(x =>
                new TopicViewModel
                {
                    Id = x.Id,
                    Name = x.Name
                });
            return View(viewModel);
        }

        //POST: Add topic
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddTopicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var errors = "";
                foreach (var modelStateVal in ViewData.ModelState.Values)
                {
                    foreach (var error in modelStateVal.Errors)
                    {
                        errors += error.ErrorMessage;
                    }
                }
                TempData["AddTErr"] = errors;
                return RedirectToAction("Topics");
            }
            var teacher = this.userService.GetTeacherByAppUserId(this.User.Identity.GetUserId());
            this.topicService.Add(
                new Topic
                {
                    Name = model.Name,
                    TeacherId = teacher.Id
                });
            return RedirectToAction("Topics");
        }

        //GET: Type questions
        [HttpGet]
        public ActionResult TypeQuestions(int id)
        {
            if (BellongToCurrentUser(id, this.User.Identity.GetUserId()))
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Topics");
                }
                var viewModel = new TypeQuestionsViewModel
                {
                    TopicId = id,
                    TopicName = this.topicService.GetById(id).Name
                };
                return View(viewModel);
            }
            return Redirect("/");
        }

        //POST: Delete close topic
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int topicId)
        {
            if (BellongToCurrentUser(topicId, this.User.Identity.GetUserId()))
            {
                try
                {
                    this.topicService.Delete(topicId);
                }
                catch
                {
                    TempData["DelError"] = Common.SomeoneUseThisTopic;
                    return Redirect("/Topic/TypeQuestions/" + topicId);
                }
                return Redirect("/Topic/Topics");
            }
            return Redirect("/");
        }

        //Check if the topic belongs to current user
        private bool BellongToCurrentUser(int id,string userId)
        {
            return this.topicService.GetById(id).Teacher.ApplicationUserId == userId;
        }
    }
}

KTraining/Views/Topic/AddTopic.cshtml
@model KTraining.Models.AddTopicViewModel
@{
    ViewBag.Title = "Add topic";
}

<h2>@KTraining.Resources.Views.Topic.AddTopic</h2><hr />
<div >
    @using (Html.BeginForm("Add", "Topic", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
               
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                 <div class="error">
                    @TempData["AddTErr"]
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@KTraining.Resources.Views.Common.Add" class="btn btn-default" />
            </div>
        </div>
    }
</div>
<link href="~/Content/Styles/Topic.css" rel="stylesheet" />

KTraining/Views/Topic/Topics.cshtml
@model IEnumerable<KTraining.Models.TopicViewModel>
@{
    ViewBag.Title = "Topics";
}


<div class="row">
    <div class="col-md-6 topic-panel">
        <h2>@KTraining.Resources.Views.Topic.Topics</h2>
        <hr />
        @foreach (var item in Model)
        {
            <div class="topic">
                <a href="/Topic/TypeQuestions/@item.Id">@item.Name</a>
            </div>
        }
    </div>
    <div class="col-md-6">
        @Html.Partial("AddTopic", new KTraining.Models.AddTopicViewModel())
    </div>
</div>
<link href="~/Content/Styles/Topic.css" rel="stylesheet" />

KTraining/Views/Topic/TypeQuestions.cshtml
@model KTraining.Models.TypeQuestionsViewModel
@{
    ViewBag.Title = "Types";
}

<div>
    <div>
        <h2>@Model.TopicName</h2>
        @using (Html.BeginForm("Delete", "Topic", FormMethod.Post, new { @role = "form" }))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="topicId" value="@Model.TopicId" />
            <input type="submit" class="btn btn-danger" value="@KTraining.Resources.Views.Topic.DeleteTopic" />
        }
    </div>
    <div class="error">
        @TempData["DelError"]
    </div>
    <h3>@KTraining.Resources.Views.Question.Questions</h3>
    <div>
        <a class="font-size-18" href="/CloseQuestion/Questions/@Model.TopicId">@KTraining.Resources.Views.Question.CloseQuestions</a>
    </div>
    <div>
        <a class="font-size-18" href="/OpenQuestion/Questions/@Model.TopicId">@KTraining.Resources.Views.Question.OpenQuestions</a>
    </div>
</div>
<link href="~/Content/Styles/Topic.css" rel="stylesheet" />