KTraining/Models/TestViewModel.cs
using KTreining.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KTraining.Models
{
    public class TestViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }
    }

    public class SelectTestViewModel
    {
        public List<ManualTest> ManualTests { get; set; }

        public List<AutomaticTest> AutomaticTests { get; set; }
    }

    public class UnsolvedTestsViewModel
    {
        public List<ManualTestForSolving> ManualTests { get; set; }

        public List<AutomaticTestForSolving> AutomaticTests { get; set; }
    }
}

KTraining/Controllers/CheckManualTestController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Models;
using KTreining.Model;

namespace KTraining.Controllers
{
    [Authorize(Roles="Teacher")]
    public class CheckManualTestController : BaseController
    {
        // GET: CheckManualTest
        [HttpGet]
        public ActionResult Tests()
        {
            var teacher=this.userService.GetTeacherByAppUserId(this.User.Identity.GetUserId());
            var tests = this.solvedManualTestService.GetForTeacher(teacher.Id)
                .Where(x=>x.IsChecked==false)
                .OrderBy(x=>x.Course.Name)
                .ToList().ConvertAll(x =>
                new SolvedManualTestShowViewModel
                {
                     CourseName=x.Course.Name,
                     CourseId=x.CourseId.Value,
                     StudentId=x.Student.ApplicationUserId,
                     Id=x.Id,
                     Name=x.Test.Title,
                     StudentName = x.Student.ApplicationUser.FirstName + " "+
                                    x.Student.ApplicationUser.SecondName +" "+
                                    x.Student.ApplicationUser.LastName
                });
            return View(tests);
        }

        [HttpGet]
        public JsonResult CountTests()
        {
            var teacher = this.userService.GetTeacherByAppUserId(this.User.Identity.GetUserId());
            var tests = this.solvedManualTestService.GetForTeacher(teacher.Id)
                .Where(x => x.IsChecked == false)
                .OrderBy(x => x.Course.Name)
                .ToList();
            return Json(tests.Count,JsonRequestBehavior.AllowGet);
        }

        //GET: Check test
        [HttpGet]
        public ActionResult CheckTest(int id)
        {
            if (BelongToCurrentUser(id, this.User.Identity.GetUserId()))
            {
                var test = this.solvedManualTestService.GetById(id);
                var viewModel = new SolvedManualTestCheckViewModel
                {
                    Id = test.Id,
                    Student = test.Student,
                    MaxPoints = this.manualTestService.MaxPoints(test.Test.Id),
                    SolvedCloseQuestions = test.SolvedCloseQuestions.ToList(),
                    SolvedOpenQuestions = test.SolvedOpenQuestions.ToList(),
                    TestTitle = test.Test.Title,
                    Rate = test.Test.Rate
                };

                foreach (var item in viewModel.SolvedOpenQuestions)
                {
                    item.OpenQuestion.Images = this.cloudinaryService.AddPathToQuestionImageName(item.OpenQuestion.Images);
                }

                foreach (var item in viewModel.SolvedCloseQuestions)
                {
                    item.CloseQuestion.Images = this.cloudinaryService.AddPathToQuestionImageName(item.CloseQuestion.Images);
                    foreach (var an in item.CloseQuestion.Answers)
                    {
                        an.Images = this.cloudinaryService.AddPathToQuestionImageName(an.Images);
                    }
                }
                return View(viewModel);
            }
            return Redirect("/CheckManualTest/Tests");
        }

        //POST:Check tests
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CheckTest(SolvedManualTestCheckViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.SolvedOpenQuestions != null)
            {
                foreach (var item in model.SolvedOpenQuestions)
                {
                    this.solvedOpenQuestionService.SetPoints(item.Id, item.Points);
                }
            }
            var solvedTest = this.solvedManualTestService.GetById(model.Id);
            double yourPoints = this.solvedManualTestService.GetPointForTest(solvedTest.Id);
            double allPoints = this.manualTestService.MaxPoints(solvedTest.TestId);
            var testRate = solvedTest.Test.Rate;
            double mark = this.testService.CalculateMark(allPoints, yourPoints, testRate);
            this.solvedManualTestService.SetMark(solvedTest.Id, mark);
            this.markService.Add(new Mark
                {
                    CourseId = solvedTest.CourseId.Value,
                    Date = DateTime.Now,
                    MarkNum = mark,
                    StudentId = model.Student.Id
                });
            this.notificationService.Add(new Notification
            {
                UserId = model.Student.ApplicationUserId,
                Content = "^d482501cd64540118d525ea74747a692^(" + solvedTest.Course.Name + " - " + mark + ")",
                Link = "/Mark/Marks"

            });
            this.solvedManualTestService.SetChecked(solvedTest.Id);
            return Redirect("/CheckManualTest/Tests");
        }
        
        //Check if the solved manual test belongs to current user
        private bool BelongToCurrentUser(int id,string userId)
        {
           return this.solvedManualTestService.GetById(id).Course.Teacher.ApplicationUserId == userId;
        }
    }
}

KTraining/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Models;

namespace KTraining.Controllers
{
    public class TestController : BaseController
    {
        // GET: Type test
        [Authorize(Roles = "Teacher")]
        public ActionResult Type()
        {
            return View();
        }

        //GET: Unsolved tests for student
        [Authorize(Roles = "Student")]
        [HttpGet]
        public ActionResult UnsolvedTests()
        {
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            var viewModel = new UnsolvedTestsViewModel
            {
                AutomaticTests = student.AutomaticTestsToSolve.ToList().OrderBy(x => x.Course.Name).ToList(),
                ManualTests = student.ManualTestsToSolve.ToList().OrderBy(x => x.Course.Name).ToList()
            };
            return View(viewModel);
        }

        //GET: Get count of unsolved tests
        [Authorize(Roles = "Student")]
        [HttpGet]
        public JsonResult CountUnsolvedTests()
        {
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            var count = student.AutomaticTestsToSolve.Count + student.ManualTestsToSolve.Count;
            return Json(count, JsonRequestBehavior.AllowGet);
        }

    }
}

KTraining/Views/CheckManualTest/CheckTest.cshtml
@model KTraining.Models.SolvedManualTestCheckViewModel

@{
    ViewBag.Title = "Check test";
}
<div>
    @using (Html.BeginForm("CheckTest", "CheckManualTest", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
       <a  href="/User/UserDetails/@Model.Student.ApplicationUserId"> <h3>@Model.Student.ApplicationUser.FirstName  @Model.Student.ApplicationUser.SecondName  @Model.Student.ApplicationUser.LastName </h3></a>
        <h4>@Model.TestTitle</h4>
        <br />
    <div>
        <ol type="1">
           @foreach(var item in Model.SolvedCloseQuestions)
            {
                <li>
                    <div>
                        <div class="row row-modify">
                            <div class="col-md-10">@Html.Raw(item.CloseQuestion.Content)</div>
                            <div>
                                @if (!(item.SelectedAnswers.Where(x => x.Correct == true).Count()
                                == item.CloseQuestion.Answers.Where(x => x.Correct == true).Count() &&
                                item.SelectedAnswers.Count()
                                == item.CloseQuestion.Answers.Where(x => x.Correct == true).Count()))
                                {
                                    <input type="text" class="test-point" max="@item.CloseQuestion.Points" value="0" disabled />
                                    <span> @KTraining.Resources.Views.Common.Points</span>
                                }
                                else
                                {
                                    <input disabled type="text" class="test-point" value="@item.CloseQuestion.Points" />
                                    <span> @KTraining.Resources.Views.Common.Points</span>
                                   
                                }
                            </div>
                        </div>
                        <div>
                            @foreach (var im in item.CloseQuestion.Images)
                            {
                                <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                            }
                        </div>

                        <div>
                            <ol type="a">
                                @foreach (var an in item.CloseQuestion.Answers)
                                {
                                    <li>
                                        <div>
                                            @if (an.Correct)
                                            {
                                                if (item.SelectedAnswers.Contains(an))
                                                {
                                                    <span style="font-size: 150%; color:green" class="glyphicon glyphicon-ok answerCircle"></span>
                                                }
                                                else
                                                {
                                                    <span style="font-size: 150%; color:green" class="glyphicon glyphicon-ok "></span>
                                                }

                                            }
                                            else if (an.Correct == false)
                                            {
                                                if (item.SelectedAnswers.Contains(an))
                                                {
                                                    <span style="font-size: 150%; color:red" class="glyphicon glyphicon-remove answerCircle"></span>
                                                }
                                                else
                                                {
                                                    <span style="font-size: 150%; color:red" class="glyphicon glyphicon-remove "></span>
                                                }
                                            }
                                            <span>@Html.Raw(an.Content)</span>
                                        </div>
                                        <div>
                                            @foreach (var im in an.Images)
                                            {
                                                <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                                            }
                                        </div>
                                    </li>
                                }
                            </ol>
                            <br />
                        </div>
                    </div>
                    <hr />
                </li>
            }
            @for (int i = 0; i < @Model.SolvedOpenQuestions.Count; i++)
            {
                <li>
                    <div>
                        <div class="row row-modify">
                            <div class="col-md-10">@Html.Raw(Model.SolvedOpenQuestions[i].OpenQuestion.Content)</div>
                            <div>
                                @Html.TextBoxFor(m => m.SolvedOpenQuestions[i].Points, new { @class = "test-point", @max = @Model.SolvedOpenQuestions[i].OpenQuestion.Points, @value = "0" })
                                <span> @KTraining.Resources.Views.Common.Points. (@Model.SolvedOpenQuestions[i].OpenQuestion.Points max)</span>
                                @Html.HiddenFor(m => m.SolvedOpenQuestions[i].Id)
                            </div>
                        </div>
                        <div>
                            @foreach (var im in Model.SolvedOpenQuestions[i].OpenQuestion.Images)
                            {
                                <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>

                            }
                        </div>

                        <div class="row row-modify">
                            <div class="col-md-12 overflow">
                                <div>@KTraining.Resources.Views.Question.Answer:</div>
                                @Html.Raw(Model.SolvedOpenQuestions[i].Answer)
                            </div>
                        </div>
                    </div>
                    <hr />
                </li>
            }
        </ol>
    </div>
        <div class="markS">
        </div>
        @Html.HiddenFor(m => m.MaxPoints, new { @class = "maxPoints" })
        @Html.HiddenFor(m => m.Rate, new { @class = "rate" })
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.Student.Id)
        @Html.HiddenFor(x=>x.Student.ApplicationUserId)
        <input type="submit" value="@KTraining.Resources.Views.Common.Ready" class="btn btn-primary check-btn"/>
    }
</div>
<script src="~/Scripts/KTrainingScripts/CheckTest.js"></script>
<link href="~/Content/Styles/CheckManualTest.css" rel="stylesheet" />

KTraining/Views/CheckManualTest/Tests.cshtml
@model List<KTraining.Models.SolvedManualTestShowViewModel>
@{
    ViewBag.Title = "Tests";
}

<h2>@KTraining.Resources.Views.Test.TestsForCheking</h2>
<div class="container row">
    @for (int i = 0; i < Model.Count; i++)
    {
        if (i == 0)
        {
            <div class="col-md-7">
                <a href="/Post/Posts/@Model[i].CourseId"> <h2>@Model[i].CourseName</h2></a>
            </div>
            <div class="col-md-12">
                <hr />
            </div>
        }
        else if (Model[i].CourseName != Model[i - 1].CourseName)
        {
            <div class="col-md-7">
                 <a href="/Post/Posts/@Model[i].CourseId"> <h2>@Model[i].CourseName</h2></a>
             </div>
            <div class="col-md-12">
                <hr />
            </div>
        }
        <div class="panel panel-default col-md-7 margin-left-20">
            <div>
                <div class="col-md-9 margin-bottom-5">
                    <div>
                        <h4> @Model[i].Name</h4>
                    </div>
                    <div>
                        <a href="/User/UserDetails/@Model[i].StudentId"> @Model[i].StudentName</a>
                    </div>
                </div>
                <div class="col-md-2 margin-top-13px">
                    @using (Html.BeginForm("CheckTest", "CheckManualTest", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@Model[i].Id" />

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="@KTraining.Resources.Views.Common.Check" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>
<link href="~/Content/Styles/CheckManualTest.css" rel="stylesheet" />