KTraining/Models/OpenQuestionViewModel.cs
using KTraining.Resources.ViewModels;
using KTreining.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTraining.Models
{
    public class OpenQuestionFullViewModel
    {
        public List<Image> Images { get; set; }

        public int Id { get; set; }

        [Required]
        [Display(
            Name = "QuestionN",
            ResourceType = typeof(Question)
            )]
        [AllowHtml]
        public string Content { get; set; }

        public virtual Topic Topic { get; set; }

        [Display(
            Name = "Points",
            ResourceType = typeof(Question)
            )]
        public double Points { get; set; }

        [Url]
        [Display(
            Name = "Help",
            ResourceType = typeof(Common)
            )]
        public string HelpLink { get; set; }
    }

    public class OpenQuestionsViewModel
    {
        public int TopicId { get; set; }
        public List<OpenQuestionViewModel> Questions { get; set; }
    }

    public class OpenQuestionViewModel
    {
        public int Id { get; set; }

        public string Content { get; set; }
    }

    public class AddOpenQuestionViewModel
    {
        [Required(
            ErrorMessageResourceName = "FieldQuestionRequired",
            ErrorMessageResourceType=typeof(Question)
            )]
        [AllowHtml]
        [Display(
         Name = "QuestionN",
         ResourceType = typeof(Question)
         )]
        public string Content { get; set; }

        public int TopicId { get; set; }

        [Required(
            ErrorMessageResourceName = "FieldPointsRequired",
            ErrorMessageResourceType=typeof(Question)
            )]
        [Display(
            Name = "Points",
            ResourceType = typeof(Question)
            )]
        public double Points { get; set; }

        [Display(
            Name = "Pictures",
            ResourceType=typeof(Common)
            )]
        public HttpPostedFileBase[] Images { get; set; }

        [Url]
        [Display(
           Name = "Help",
           ResourceType = typeof(Common)
           )]
        public string HelpLink { get; set; }
    }

    public class SelectOpenQuestionViewModel
    {
        public OpenQuestion Question { get; set; }

        public bool IsSelected { get; set; }
    }

    public class SolveOpenQuestionViewModel
    {
        [Required]
        public int QuestionId { get; set; }

        public string Content { get; set; }

        public int Index { get; set; }

        public ICollection<Image> Images { get; set; }

        [Required]
        public int SolvedTestId { get; set; }

        [Required]
        public int SolvedQuestionId { get; set; }

        [AllowHtml]
        public string Answer { get; set; }
    }
}

KTraining/Controllers/ManualTestStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTreining.Model;
using KTraining.Service;
using KTraining.Models;

namespace KTraining.Controllers
{
    [Authorize(Roles = "Student")]
    public class ManualTestStudentController : BaseController
    {
        //GET: Start solving
        [HttpPost]
        public ActionResult StartTest(int id)
        {
            var test = this.manualTestForSolvingService.GetById(id);
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            if (test.StudentId == student.Id)
            {
                var sId = this.solvedManualTestService.Add(
                    new SolvedManualTest
                    {
                        StudentId = student.Id,
                        StartTime = DateTime.Now,
                        CourseId = test.CourseId,
                        TestId = test.TestId.Value,
                        SolvedCloseQuestions = OtherFunctions
                            .Shuffle<CloseQuestion>(test.Test.CloseQuestions.ToList())
                            .ToList()
                            .ConvertAll(x => new SolvedCloseQuestion
                            {
                                CloseQuestionId = x.Id
                            }),
                        SolvedOpenQuestions = OtherFunctions
                       .Shuffle<OpenQuestion>(test.Test.OpenQuestions.ToList())
                       .ToList()
                       .ConvertAll(x => new SolvedOpenQuestion
                       {
                           OpenQuestionId = x.Id
                       })
                    });
                var newTest = new StartManualTestViewModel
                {
                    Id = test.Id,
                    TeacherName = test.Test.Teacher.ApplicationUser.FirstName + test.Test.Teacher.ApplicationUser.LastName,
                    Title = test.Test.Title,
                    Time = test.Test.Time,
                    SolvedTestId = sId,
                    CountQuestion = test.Test.CloseQuestions.Count + test.Test.OpenQuestions.Count

                };
                this.studentService.RemoveManualTestToSolve(student.Id, id, test.CourseId);
                return View(newTest);
            }
            return Redirect("/");
        }

        //GET: Get question
        [HttpGet]
        public ActionResult Question(int questionIndex, int solvedTestId)
        {
            var solvedTest = this.solvedManualTestService.GetById(solvedTestId);
            if (questionIndex >= solvedTest.SolvedCloseQuestions.Count)
            {
                if (questionIndex >= solvedTest.SolvedOpenQuestions.Count + solvedTest.SolvedCloseQuestions.Count)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                var solvedOpenQuestion = this.solvedOpenQuestionService.GetOpenQuestionByManualTestAndIndex(solvedTestId, questionIndex - solvedTest.SolvedCloseQuestions.Count);
                var newOpenQuestion = new SolveOpenQuestionViewModel
                {
                    Content = solvedOpenQuestion.OpenQuestion.Content,
                    QuestionId = solvedOpenQuestion.OpenQuestion.Id,
                    Index = questionIndex,
                    Images = this.cloudinaryService.AddPathToQuestionImageName(solvedOpenQuestion.OpenQuestion.Images).ToList(),
                    SolvedTestId = solvedTestId,
                    SolvedQuestionId = solvedOpenQuestion.Id
                };
                return PartialView("OpenQuestion", newOpenQuestion);

            }
            var solvedQuestion = this.solvedCloseQuestionService.GetCloseQuestionByManualTestAndIndex(solvedTestId, questionIndex);
            var newQuestion = new SolveCloseQuestionViewModel
            {
                Answers = solvedQuestion.CloseQuestion.Answers.ToList().ConvertAll(x => new CloseAnswer
                {
                    Content = x.Content,
                    Correct = x.Correct,
                    Id = x.Id,
                    Images = this.cloudinaryService.AddPathToQuestionImageName(x.Images),
                    Question = x.Question,
                    QuestionId = x.QuestionId
                }),
                Content = solvedQuestion.CloseQuestion.Content,
                QuestionId = solvedQuestion.CloseQuestion.Id,
                Index = questionIndex,
                Images = this.cloudinaryService.AddPathToQuestionImageName(solvedQuestion.CloseQuestion.Images).ToList(),
                SolvedTestId = solvedTestId,
                SolvedQuestionId = solvedQuestion.Id
            };
            newQuestion.Answers = OtherFunctions.Shuffle<CloseAnswer>(newQuestion.Answers.ToList());
            var correctAnswers = newQuestion.Answers.Where(x => x.Correct == true).Count();
            if (correctAnswers > 1)
            {
                newQuestion.IsMultiple = true;
                newQuestion.MultipleSelected = new List<MultipleAnswer>();
                foreach (var item in newQuestion.Answers)
                {
                    newQuestion.MultipleSelected.Add(new MultipleAnswer
                    {
                        AnswerId = item.Id,
                        IsSelected = false
                    });
                }
                newQuestion.MultipleSelected.ToList();
            }
            return PartialView(newQuestion);
        }

        //POST: Send answer for close question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendAnswer(SolveCloseQuestionViewModel question)
        {
            if (question.SolvedTestId == 0 || question.SolvedQuestionId == 0 || question.QuestionId == 0)
            {
                return RedirectToAction("Question", new { questionIndex = question.Index, solvedTestId = question.SolvedTestId });
            }
            if (question.SelectedAnswer != 0)
            {
                this.solvedCloseQuestionService.AddSelectedAnswer(new List<int> { question.SelectedAnswer }, question.SolvedQuestionId);
            }
            else if (question.MultipleSelected != null)
            {
                this.solvedCloseQuestionService.AddSelectedAnswer(question.MultipleSelected.Where(x => x.IsSelected == true)
                    .Select(x => x.AnswerId).ToList()
                    , question.SolvedQuestionId);
            }
            return RedirectToAction("Question", new { questionIndex = question.Index + 1, solvedTestId = question.SolvedTestId });
        }

        //POST: Check time for test
        [HttpPost]
        public JsonResult CheckTime(int solvedTestId)
        {
            var test = this.solvedManualTestService.GetById(solvedTestId);
            var startTime = test.StartTime;
            var time = test.Test.Time;
            var endTime = startTime.AddMinutes(time);
            if (DateTime.Now < endTime)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        //POST: Send answer for open question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendAnswerOpen(SolveOpenQuestionViewModel question)
        {
            if (question.SolvedTestId == 0 || question.SolvedQuestionId == 0 || question.QuestionId == 0)
            {
                return RedirectToAction("Question", new { questionIndex = question.Index, solvedTestId = question.SolvedTestId });
            }
            if (question.Answer != null)
            {
                this.solvedOpenQuestionService.AddAnswer(question.SolvedQuestionId, question.Answer);
            }
            return RedirectToAction("Question", new { questionIndex = question.Index + 1, solvedTestId = question.SolvedTestId });
        }

        //POST: End test
        [HttpGet]
        public ActionResult EndTest(int id)
        {
            if (id != 0 && BellongToCurrentUser(id, this.User.Identity.GetUserId()))
            {
                var solvedTest = this.solvedManualTestService.GetById(id);
                this.solvedManualTestService.SetComplete(id);
                this.notificationService.Add(new Notification
                {
                    UserId = solvedTest.Course.Teacher.ApplicationUserId,
                    Content = "^q27e30c9e92b4b11bb5a420f7a98e29d^",
                    Link = "/CheckManualTest/Tests"

                });
                return View("ResultOfTest");
            }
            return Redirect("/");
        }

        //Check if the solved manual test belongs to current user
        private bool BellongToCurrentUser(int id, string userId)
        {
            return this.solvedManualTestService.GetById(id).Student.ApplicationUserId == userId;
        }
    }
}

KTraining/Controllers/OpenQuestionController.cs
using KTraining.Models;
using KTraining.Service;
using KTreining.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Resources.Controllers;

namespace KTraining.Controllers
{
    [Authorize(Roles="Teacher")]
    public class OpenQuestionController : BaseController
    {
        // GET:Get Open Questions for topic
        [HttpGet]
        public ActionResult Questions(int id)
        {
            if (BellongToCurrentUserT(id, this.User.Identity.GetUserId()))
            {
                var questions = this.openQuestionService.GetForTopic(id);
                var viewModel = new OpenQuestionsViewModel
                {
                    TopicId = id,
                    Questions = questions.ToList()
                    .ConvertAll(x =>
                    new OpenQuestionViewModel
                    {
                        Id = x.Id,
                        Content = x.Content
                    })
                };
                return View(viewModel);
            }
            return Redirect("/");
        }

        //GET: Add open question
        [HttpGet]
        public ActionResult Add(int id)
        {
            if (BellongToCurrentUserT(id, this.User.Identity.GetUserId()))
            {
                return View(new AddOpenQuestionViewModel { TopicId = id, Points = 2 });
            }
            return Redirect("/");
        }

        //POST: Add question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddOpenQuestionViewModel model)
        {
            if (model.Content!=null&& OtherFunctions.IsHasJS(model.Content))
            {
                ModelState.AddModelError("", Common.FiledQDanger);
                return View(model);
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var questionId = this.openQuestionService.Add(new OpenQuestion
            {
                Content = model.Content,
                Points = model.Points,
                TopicId = model.TopicId,
                HelpLink = model.HelpLink
            });
            int id;
            foreach (var file in model.Images)
            {
                if (file != null)
                {
                    var uploadResult = this.cloudinaryService.UploadImage(file.FileName, file.InputStream);
                    id = this.imageService.Add(new Image
                    {
                        Name = file.FileName,
                        Source = uploadResult
                    });
                    this.openQuestionService.AddImage(questionId, id);
                }
            }
            return Redirect("/OpenQuestion/Questions/" + model.TopicId);
        }

        //GET: Get a question
        [HttpGet]
        public ActionResult Question(int id)
        {
            if (BellongToCurrentUserQ(id, this.User.Identity.GetUserId()))
            {
                var question = this.openQuestionService.GetById(id);
                var viewModel = new OpenQuestionFullViewModel
                {
                    Content = question.Content,
                    Images = this.cloudinaryService.AddPathToQuestionImageName(question.Images).ToList(),
                    Points = question.Points,
                    Topic = question.Topic,
                    Id = question.Id
                };
                return View(viewModel);
            }
            return Redirect("/");
        }

        //POST: Edit a question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OpenQuestionFullViewModel model)
        {
            if (model.Content!=null&& OtherFunctions.IsHasJS(model.Content))
            {
                TempData["ConError"] = Common.FiledQDanger;
                return Redirect("/OpenQuestion/Question/" + model.Id);
            }
            if (!ModelState.IsValid)
            {
                if (model.Content == null)
                {
                    TempData["ConError"] = Common.FieldQRequired;
                }
                if(model.Points==0)
                {
                    TempData["PointError"] = Common.ShouldBeNum;
                }
                return Redirect("/OpenQuestion/Question/" + model.Id);
            }
            this.openQuestionService.Update(new OpenQuestion
            {
                Content = model.Content,
                Points = model.Points,
                Id = model.Id,
                HelpLink = model.HelpLink
            });
            return Redirect("/OpenQuestion/Question/" + model.Id);
        }

        //POST: Delete open question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int questionId)
        {
            var topicId = this.openQuestionService.GetById(questionId).TopicId;
            try
            {
                this.openQuestionService.Delete(questionId);
            }
            catch
            {
                TempData["DelError"] = Common.SomeoneUserThisQ;
                return Redirect("/OpenQuestion/Question/" + questionId);
            }
            return Redirect("/OpenQuestion/Questions/" + topicId);
        }

        //Check if the open question belongs to current user
        private bool BellongToCurrentUserQ(int id, string userId)
        {
            return this.openQuestionService.GetById(id).Topic.Teacher.ApplicationUserId == userId;
        }

        //Check if the topic belongs to current user
        private bool BellongToCurrentUserT(int id, string userId)
        {
            return this.topicService.GetById(id).Teacher.ApplicationUserId == userId;
        }
    }
}

KTraining/Views/ManualTestStudent/OpenQuestion.cshtml
@model KTraining.Models.SolveOpenQuestionViewModel
@{
    ViewBag.Title = "Question";
}
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left font-size-17">
                @(Model.Index + 1).@Html.Raw(Model.Content)
            </div>
        </div>
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left">
                @foreach (var im in Model.Images)
                {
                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                }
            </div>

        </div>
                @using (Html.BeginForm("SendAnswerOpen", "ManualTestStudent", FormMethod.Post, new { id = "idForm", @class = "navbar-left navbar-left col-xs-12 col-centered col-fixed" }))
                {
                    @Html.AntiForgeryToken()
                    <textarea name="textArea"></textarea>
                    @Html.HiddenFor(m => m.Answer, new { @class = "hiddenArr" })
                    @Html.HiddenFor(m => m.Index, new { @class = "form-control index" })
                    @Html.HiddenFor(m => m.SolvedQuestionId, new { @class = "form-control" })
                    @Html.HiddenFor(m => m.SolvedTestId, new { @class = "form-control" })
                    @Html.HiddenFor(m => m.QuestionId, new { @class = "form-control" })
                    <input type="button" class="btn btn-default margin-top" value="@KTraining.Resources.Views.Common.Next" id="next" />
                }
    </div>
</div>
<link href="~/Content/Styles/ManualTestStudent.css" rel="stylesheet" />
@Scripts.Render("~/Scripts/tinymce/tinymce.min.js")
<script src="~/Scripts/KTrainingScripts/InitTinyMCE.js"></script>
<script>
    $("#next").click(function () {
        $('.hiddenArr').val(tinyMCE.get('textArea').getContent());
        GetQuestion();
        
    });
    function GetQuestion() {
        $.ajax({
            type: "POST",
            url: "/ManualTestStudent/SendAnswerOpen",
            data: $("#idForm").serialize(),
            traditional: true,
            success: function (data) {
                if (data === true) {
                    window.location.href = "/ManualTestStudent/EndTest/@Model.SolvedTestId";
                }
                else {
                    $("#question").html(data);
                    $("p").addClass("par-in");
                }
            }
        });
    }
</script>

KTraining/Views/ManualTestStudent/Question.cshtml
@model KTraining.Models.SolveCloseQuestionViewModel
@{
    ViewBag.Title = "Question";
}
<br />
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left font-size-17">
                @(Model.Index + 1).@Html.Raw(Model.Content)
            </div>
        </div>
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left">
                @foreach (var im in Model.Images)
                {
                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                }
            </div>

        </div>
        @using (Html.BeginForm("SendAnswer", "ManualTestStudent", FormMethod.Post, new { id = "idForm", @class = "navbar-left col-xs-12 col-centered col-fixed " }))
         {
           @Html.AntiForgeryToken()
            if(!Model.IsMultiple)
            { 
                foreach (var item in Model.Answers)
                {
                    <div class=" answer-div ">
                        <div class="text-align-left">
                            <div class="col-xs-1 radio-btn padding-0">
                                @Html.RadioButtonFor(x => x.SelectedAnswer, item.Id, new { @id = @item.Id, @class = " answer-label" })
                            </div>
                            <div class="col-xs-11 padding-0 "><label class="font-size-15  answer-label" for="@item.Id">@Html.Raw(@item.Content)</label></div>

                            <div class="text-align-left row margin-0">
                                @foreach (var im in item.Images)
                                {
                                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                                }
                            </div>
                        </div>
                    </div>
                }
              }
              else
            {
                int index=0;
                foreach (var item in Model.Answers)
                {
                    <div class=" answer-div ">
                        <div class="text-align-left">
                            <div class="col-xs-1 radio-btn padding-0">      
                             @Html.HiddenFor(m => Model.MultipleSelected[index].AnswerId, new { @class = "form-control" })
                                @Html.CheckBoxFor(m => Model.MultipleSelected[index].IsSelected, new { @class = "form-control" ,style="zoom:0.5"})
                            </div>
                            <div class="col-xs-11 padding-0 "><label class="font-size-15  answer-label" for="@item.Id">@Html.Raw(item.Content)</label></div>

                            <div class="text-align-left row margin-0">
                                @foreach (var im in item.Images)
                                {
                                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                                }
                            </div>
                        </div>
                    </div>
                    index++;
                }
            }
            @Html.HiddenFor(m => m.Index, new { @class = "form-control index" })
            @Html.HiddenFor(m => m.SolvedQuestionId, new { @class = "form-control" })
            @Html.HiddenFor(m => m.Answers, new { @class = "form-control" })
            @Html.HiddenFor(m => m.SolvedTestId, new { @class = "form-control" })
            @Html.HiddenFor(m => m.QuestionId, new { @class = "form-control" })
      
            <input type="button" class="btn btn-default" value="@KTraining.Resources.Views.Common.Next" id="next" />
         }
    </div>
    </div>

<script>
    $("#next").click(function () {
        GetQuestion();

    });
    function GetQuestion() {
        $.ajax({
            type: "POST",
            url: "/ManualTestStudent/SendAnswer",
            data: $("#idForm").serialize(),
            traditional: true,
            success: function (data) {
                if (data === true) {
                    window.location.href = "/ManualTestStudent/EndTest/@Model.SolvedTestId";
                }
                else {
                    $("#question").html(data);
                    $("p").addClass("par-in");
                    var a = parseInt($(".questionNum").html());
                    a++;
                    $(".questionNum").html(a);
                }
            }
        });
    }
</script>

<link href="~/Content/Styles/ManualTestStudent.css" rel="stylesheet" />

KTraining/Views/ManualTestStudent/ResultOfTest.cshtml
@{
    ViewBag.Title = "Result";
}
<br />
<br />
<div>
   <h4> @KTraining.Resources.Views.Test.ComlManTestDes</h4>
</div>

KTraining/Views/ManualTestStudent/StartTest.cshtml
@model KTraining.Models.StartManualTestViewModel
@{
    ViewBag.Title = "Start";
}
<div class="font-size-22" id="timer"></div>
<br />
<div class="border-q">
    <div class="row" style="border-bottom: 1px solid #eee;">
        <div class="col-md-12">
            <h3>@Model.Title</h3>
        </div>
        <div class="col-md-12">
            <h4>@Model.TeacherName</h4>
        </div>
        <div class="col-md-3">
            @KTraining.Resources.Views.Common.Time:
            <span id="time">
            </span>
        </div>
        <div class="col-md-12">
            @KTraining.Resources.Views.Question.Questions:
            <span class="questionNum">
                1
            </span>
            @KTraining.Resources.Views.Common.Of @Model.CountQuestion
        </div>
    </div>
    <div class="row" id="question">
        <img class="loading-m" src="~/Content/loading.gif" />
    </div>
</div>

<link href="~/Content/Styles/ManualTestStudent.css" rel="stylesheet" />
<link href="~/Content/jquery.fancybox.css" rel="stylesheet" />
@section scripts{
@Scripts.Render("~/Scripts/jquery.mousewheel.pack.js")
@Scripts.Render("~/Scripts/jquery.fancybox.pack.js")
    <script>
    $(window).bind('beforeunload', function(){
        window.open("/ManualTestStudent/EndTest/@Model.SolvedTestId");
    });

        var time=@Model.Time;
        $("#time").html(time+" @KTraining.Resources.Views.Common.Minutes");
    setInterval(function() {
        $.ajax({
            type: "POST",
            url: "/ManualTestStudent/CheckTime",
            data: {solvedTestId:@Model.SolvedTestId },
            traditional: true,
            success: function (data) {
                if(data===false)
                {
                    clearInterval(this);
                    window.location.href="/ManualTestStudent/EndTest/@Model.SolvedTestId";
                }
            }
        });
        time--;
        $("#time").html("@KTraining.Resources.Views.Common.Time: "+time);
    }, 60 * 1000);

    function GetQuestion()
    {
        $.ajax({
            type: "GET",
            url: "/ManualTestStudent/Question",
            data: {questionIndex:0,solvedTestId:@Model.SolvedTestId },
            traditional: true,
            success: function (data) {
                $("#question").html(unescape(data));
                $('.fancybox').fancybox();
                $("p").addClass("par-in");
            }
        });
    }
    GetQuestion();

    $('.fancybox').fancybox();
</script>
}