KTraining/Controllers/LevelAutomaticTestController.cs
using KTreining.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Service;
using KTraining.Models;
using Newtonsoft.Json;

namespace KTraining.Controllers
{
    [Authorize(Roles = "Student")]
    public class LevelAutomaticTestController : BaseController
    {
        //GET: Start solving
        [HttpGet]
        public ActionResult StartTest(int id)
        {
            var test = this.levelTestForSolvingService.GetById(id);
            this.ControllerContext.HttpContext.Response.Cookies.Add(new HttpCookie("levelId") { Value = test.CourseLevelId.ToString() });
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            if (test.StudentId == student.Id)
            {
                var sTest =
                    new SolvedAutomaticTest
                    {
                        StudentId = student.Id,
                        StartTime = DateTime.Now,
                        CourseId = test.CourseLevel.CourseId,
                        TestId = test.CourseLevel.AutomaticTestId.Value,
                        SolvedQuestions = OtherFunctions
                        .Shuffle<CloseQuestion>(test.CourseLevel.AutomaticTest.CloseQuestions.ToList())
                        .ToList()
                        .ConvertAll(x => new SolvedCloseQuestion
                        {
                            CloseQuestionId = x.Id
                        }),
                        Course = new Course { Name = test.CourseLevel.Course.Name }
                    };

                HttpCookie cookie = new HttpCookie("testForLevel");
                cookie.Value = JsonConvert.SerializeObject(sTest);
                this.ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                var newTest = new StartAutoTestViewModel
                {
                    Id = test.Id,
                    TeacherName = test.CourseLevel.AutomaticTest.Teacher.ApplicationUser.FirstName + " " + test.CourseLevel.AutomaticTest.Teacher.ApplicationUser.LastName,
                    Title = test.CourseLevel.AutomaticTest.Title,
                    Time = test.CourseLevel.AutomaticTest.Time,
                    QuestionCount = test.CourseLevel.AutomaticTest.CloseQuestions.Count

                };
                this.levelTestForSolvingService.Remove(id);
                return View(newTest);
            }

            return Redirect("/");
        }

        //GET: Get question\
        public ActionResult Question(int questionIndex)
        {
            var test = this.ControllerContext.HttpContext.Request.Cookies["testForLevel"].Value;
            var solvedTest = JsonConvert.DeserializeObject<SolvedAutomaticTest>(test);
            if (questionIndex >= solvedTest.SolvedQuestions.Count)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            var clQId = solvedTest.SolvedQuestions.ElementAt(questionIndex).CloseQuestionId;
            var solvedQuestion = this.closeQuestionService.GetById(clQId);
            var newQuestion = new SolveCloseQuestionViewModel
            {
                Answers = solvedQuestion.Answers.ToList().ConvertAll(x => new CloseAnswer
                {
                    Content = x.Content,
                    Correct = x.Correct,
                    Id = x.Id,
                    Images = this.cloudinaryService.AddPathToQuestionImageName(x.Images),
                    Question = x.Question,
                    QuestionId = x.QuestionId
                }),
                Content = solvedQuestion.Content,
                QuestionId = solvedQuestion.Id,
                Index = questionIndex,
                Images = this.cloudinaryService.AddPathToQuestionImageName(solvedQuestion.Images).ToList(),
                SolvedQuestionId = solvedQuestion.Id,
            };

            newQuestion.Answers = OtherFunctions.Shuffle<CloseAnswer>(newQuestion.Answers.ToList()).ToList();
            var correctAnswers = newQuestion.Answers.Where(x => x.Correct == true).Count();
            if (correctAnswers > 1)
            {
                newQuestion.IsMultiple = true;
                newQuestion.MultipleSelected = new List<MultipleAnswer>();
                foreach (var item in newQuestion.Answers)
                {
                    newQuestion.MultipleSelected.Add(new MultipleAnswer
                    {
                        AnswerId = item.Id,
                        IsSelected = false
                    });
                }
                newQuestion.MultipleSelected.ToList();
            }
            return PartialView(newQuestion);
        }

        //POST: Send answer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendAnswer(SolveCloseQuestionViewModel question)
        {
            if (question.SolvedQuestionId == 0 || question.QuestionId == 0)
            {
                return RedirectToAction("Question", new { questionIndex = question.Index, solvedTestId = question.SolvedTestId });
            }
            var test = this.ControllerContext.HttpContext.Request.Cookies["testForLevel"].Value;
            var solvedTest = JsonConvert.DeserializeObject<SolvedAutomaticTest>(test);
            if (question.SelectedAnswer != 0)
            {
                var q = solvedTest.SolvedQuestions.Where(x => x.CloseQuestionId == question.SolvedQuestionId).First();
                var answer = this.closeAnswerService.GetById(question.SelectedAnswer);
                q.SelectedAnswers = new List<CloseAnswer> { new CloseAnswer{ Content="",Correct=answer.Correct,Id=answer.Id,
                Images=answer.Images,QuestionId=answer.QuestionId} };
            }
            else if (question.MultipleSelected != null)
            {
                var q = solvedTest.SolvedQuestions.Where(x => x.CloseQuestionId == question.SolvedQuestionId).First();
                var answers = new List<CloseAnswer>();
                foreach (var item in question.MultipleSelected.Where(x => x.IsSelected == true).Select(x => x.AnswerId))
                {
                    var newAnswer = this.closeAnswerService.GetById(item);
                    answers.Add(new CloseAnswer
                    {
                        Content = "",
                        Correct = newAnswer.Correct,
                        Id = newAnswer.Id,
                        Images = newAnswer.Images,
                        QuestionId = newAnswer.QuestionId
                    });
                }
                q.SelectedAnswers = answers;

            }
            HttpCookie cookie = new HttpCookie("testForLevel");
            cookie.Value = JsonConvert.SerializeObject(solvedTest);
            this.ControllerContext.HttpContext.Response.Cookies.Remove("testForLevel");
            this.ControllerContext.HttpContext.Response.Cookies.Add(cookie);

            return RedirectToAction("Question", new { questionIndex = question.Index + 1 });
        }

        //POST: Check time for test
        [HttpPost]
        public JsonResult CheckTime()
        {
            var test = this.ControllerContext.HttpContext.Request.Cookies["testForLevel"].Value;
            var solvedTest = JsonConvert.DeserializeObject<SolvedAutomaticTest>(test);
            var startTime = solvedTest.StartTime;
            var time = this.automaticTestService.GetById(solvedTest.TestId).Time;
            var endTime = startTime.AddMinutes(time);
            if (DateTime.Now < endTime)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        //POST: End test
        [HttpGet]
        public ActionResult EndTest()
        {
            var test = this.ControllerContext.HttpContext.Request.Cookies["testForLevel"].Value;
            var solvedTest = JsonConvert.DeserializeObject<SolvedAutomaticTest>(test);
            double testPoints = this.solvedAutomaticTestService.GetPointForTest(solvedTest);
            double allPoints = this.automaticTestService.GetPointsForTest(solvedTest.TestId);
            var testRate = this.automaticTestService.GetById(solvedTest.TestId).Rate;
            double grade = this.testService.CalculateMark(allPoints, testPoints, testRate);
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            var level = this.courseLevelService.GetById(int.Parse(this.ControllerContext.HttpContext.Request.Cookies["levelId"].Value));
            this.markService.Add(
                new Mark
                {
                    CourseId = solvedTest.CourseId.Value,
                    MarkNum = grade,
                    StudentId = student.Id,
                    Date = DateTime.Now,
                    Description = "^c999d7d108874d94abbc95ffb2118a99^ " + level.Name
                });
            if (grade >= 3.00)
            {
                this.notificationService.Add(new Notification
                {
                    UserId = student.ApplicationUserId,
                    Content = "^ca779cae33834c0fbd4491b45e066343^ " + level.Name + "(" + solvedTest.Course.Name + "-" + grade + ")",
                    Link = "/Mark/Marks"

                });
                this.courseLevelService.AddCourseLevelToStudent(level.Id, student.Id);
                Response.Cookies.Clear();
                return View("ResultOfTest", null, new ResultViewModel { CorrectAnswers = testPoints, Grade = grade, Description = level.Name + " в курс " + level.Course.Name });
            }
            else
            {
                this.notificationService.Add(new Notification
                {
                    UserId = student.ApplicationUserId,
                    Content = "^d482501cd64540118d525ea74747a692^.(" + solvedTest.Course.Name + " - " + grade + ")",

KTraining/Views/LevelAutomaticTest/NotAccessResult.cshtml
@model KTraining.Models.ResultViewModel
@{
    ViewBag.Title = "Result";
}
<br />
<br />
<h2>@KTraining.Resources.Views.Test.NoCompleteTest @Model.Description</h2>
<div>
    @KTraining.Resources.Views.Question.CorrectAnss: @Model.CorrectAnswers
    <br />  @KTraining.Resources.Views.Common.Mark: @Model.Grade
</div>

KTraining/Views/LevelAutomaticTest/Question.cshtml
@model KTraining.Models.SolveCloseQuestionViewModel
@{
    ViewBag.Title = "Question";
}
<br />
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left font-size-17">
                @(Model.Index + 1).@Html.Raw(@Model.Content)
            </div>
        </div>
        <br />
        <div class="col-xs-12 col-centered col-fixed">
            <div class="text-align-left">
                @foreach (var im in Model.Images)
                {
                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                }
            </div>

        </div>
        @using (Html.BeginForm("SendAnswer", "LevelAutomaticTest", FormMethod.Post, new { id = "idForm", @class = "navbar-left col-xs-12 col-centered col-fixed " }))
        {
            @Html.AntiForgeryToken()
            if(!Model.IsMultiple)
            { 
                foreach (var item in Model.Answers)
                {
                    <div class=" answer-div ">
                        <div class="text-align-left">
                            <div class="col-xs-1 radio-btn padding-0">
                                @Html.RadioButtonFor(x => x.SelectedAnswer, item.Id, new { @id = @item.Id, @class = " answer-label" })
                            </div>
                            <div class="col-xs-11 padding-0 "><label class="font-size-15  answer-label" for="@item.Id">@Html.Raw(@item.Content)</label></div>

                            <div class="text-align-left row margin-0">
                                @foreach (var im in item.Images)
                                {
                                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                                }
                            </div>
                        </div>
                    </div>
                }
              }
              else
            {
                int index=0;
                foreach (var item in Model.Answers)
                {
                    <div class=" answer-div ">
                        <div class="text-align-left">
                            <div class="col-xs-1 radio-btn padding-0">      
                             @Html.HiddenFor(m => Model.MultipleSelected[index].AnswerId, new { @class = "form-control" })
                                @Html.CheckBoxFor(m => Model.MultipleSelected[index].IsSelected, new { @class = "form-control", style = "zoom:0.5" })
                            </div>
                            <div class="col-xs-11 padding-0 "><label class="font-size-15  answer-label" for="@item.Id">@Html.Raw(item.Content)</label></div>

                            <div class="text-align-left row margin-0">
                                @foreach (var im in item.Images)
                                {
                                    <a class="fancybox " href="@im.Source" title="@im.Name"><img src="@im.Source" height="70" width="90" class="tr" alt=""></a>
                                }
                            </div>
                        </div>
                    </div>
                    index++;
                }
            }
            @Html.HiddenFor(m => m.Index, new { @class = "form-control index" })
            @Html.HiddenFor(m => m.SolvedQuestionId, new { @class = "form-control" })
            @Html.HiddenFor(m => m.Answers, new { @class = "form-control" })
            @Html.HiddenFor(m => m.SolvedTestId, new { @class = "form-control" })
    @Html.HiddenFor(m => m.QuestionId, new { @class = "form-control" })
      
            <input type="button" class="btn btn-default" value="@KTraining.Resources.Views.Common.Next" id="next" />
        }
    </div>
</div>

<script>
    $("#next").click(function () {
        GetQuestion();

    });

    function GetQuestion() {
        $.ajax({
            type: "POST",
            url: "/LevelAutomaticTest/SendAnswer",
            data: $("#idForm").serialize(),
            traditional: true,
            success: function (data) {
                if (data === true) {
                    window.location.href = "/LevelAutomaticTest/EndTest";
                }
                else {
                    $("#question").html(data);
                    $("p").addClass("par-in");
                    var a = parseInt($(".questionNum").html());
                    a++;
                    $(".questionNum").html(a);

                }
            }
        });
    }
</script>

<link href="~/Content/Styles/AutomaticTestStudent.css" rel="stylesheet" />

KTraining/Views/LevelAutomaticTest/ResultOfTest.cshtml
@model KTraining.Models.ResultViewModel
@{
    ViewBag.Title = "Result";
}

<br />
<br />
<h2>@KTraining.Resources.Views.Test.CompleteTest @Model.Description</h2>
<div>
    @KTraining.Resources.Views.Question.CorrectAnss: @Model.CorrectAnswers
    <br />  @KTraining.Resources.Views.Common.Mark: @Model.Grade
</div>

KTraining/Views/LevelAutomaticTest/StartTest.cshtml
@model KTraining.Models.StartAutoTestViewModel
@{
    ViewBag.Title = "Solving";
}

<div class="font-size-22" id="timer">

</div>
<br />
<div class="q-border">
    <div class="row">
        <div class="col-md-12">
            <h3>@Model.Title</h3>
        </div>
        <div class="col-md-12">
            <h4>@Model.TeacherName</h4>
        </div>
        <div class="col-md-3">
            @KTraining.Resources.Views.Common.Time:
            <span id="time">

            </span>
        </div>
        <div class="col-md-12">
            @KTraining.Resources.Views.Question.Questions:
            <span class="questionNum">
                1
            </span>
            @KTraining.Resources.Views.Common.Of @Model.QuestionCount
        </div>
    </div>
    <div class="row" id="question">

        <img class="loading-m" src="~/Content/loading.gif" />
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery.mousewheel.pack.js"></script>
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>
    <link href="~/Content/jquery.fancybox.css" rel="stylesheet" />
    <script>

        $(window).bind('beforeunload', function(){
            window.open("/LevelAutomaticTest/EndTest");
        });

        var time=@Model.Time;
        $("#time").html(time+" @KTraining.Resources.Views.Common.Minutes");

        setInterval(function() {
            $.ajax({
                type: "POST",
                url: "/LevelAutomaticTest/CheckTime",
                traditional: true,
                success: function (data) {
                    if(data===false)
                    {
                        window.location.href="/LevelAutomaticTest/EndTest";
                    }
                }
            });
            time--;
            $("#time").html(time+ " @KTraining.Resources.Views.Common.Minutes");
        }, 60 * 1000);

        function GetQuestion()
        {
            $("#question").html("Loading ...");
            $.ajax({
                type: "GET",
                url: "/LevelAutomaticTest/Question",
                data: {questionIndex:0},
                traditional: true,
                success: function (data) {
                    $("#question").html(unescape(data));
                    $("p").addClass("par-in");
                  
                }
            });
        }
        GetQuestion();

        $('.fancybox').fancybox();

    </script>
}
<link href="~/Content/Styles/AutomaticTestStudent.css" rel="stylesheet" />